# coding: utf-8
source 'https://rubygems.org'

# Specify your gem's dependencies in todo.gemspec
gemspec

gem 'ripper-tags'
gem 'gem-ripper-tags'
gem 'guard'
gem 'guard-shell'
gem 'observer'
gem 'rev'
gem 'rcodetools'
gem 'rdefs'
gem 'pry'
gem 'pry-doc'
gem 'pry-stack_explorer'
if RUBY_VERSION >= '2.0.0'
   gem 'pry-byebug'
else
   # 以下はRuby1.9の時のみ使う(pry-byebugの代わりに)
   # debuggerは1.9以下でしか動作しない, remote は byebug で使えないようになった
   gem 'pry-debugger'
   gem 'pry-remote'
end
gem 'pry-theme'
gem 'rubocop'
gem 'ruby-lint'
gem 'method_source', ">= 0.8.2"
gem 'gist'
gem 'guard-yard'
